### ISSUE TITLE
Feature Request: Camera independent presets

### ISSUE THREAD

**Issue by janzev** [glikely/obs-ptz#113] opened 2022-11-07 23:44 UTC
It would be nice to have camera independent presets. I have older Cisco conference cams that can be controlled through serial VISCA but it seems that they do not support camera builtin presets. It would be useful if I could move the camera to absolute positions (saved on my OBS computer) when a scene becomes active instead of calling a camera saved preset.

**Comment by glikely** [comment] 2022-11-08 06:20
Duplicate of #24

**Closed by glikely** 2022-11-08 06:20 UTC
