### ISSUE TITLE
A way to invert PTZ controls

### ISSUE THREAD

**Issue by thehammer39** [glikely/obs-ptz#102] opened 2022-08-12 13:25 UTC
Currently, my camera is mounted upside down and the PTZ controls move the camera in the opposite direction.

**Comment by PoWeR-Ding** [comment] 2022-09-01 02:51
If the image is flipped, then the OBS filter can handle it.
If it is to control the flip, it needs to be updated. .

**Comment by thehammer39** [comment] 2022-09-16 16:22
I have fixed the image so it shows correctly in OBS. Now when I click the left PTZ button the camera moves to the right.

**Comment by glikely** [comment] 2022-11-07 08:51
Duplicate of #11

**Closed by glikely** 2022-11-07 08:51 UTC
