### ISSUE TITLE
is this PTZ camera supported?

### ISSUE THREAD

**Issue by AndreV84** [glikely/obs-ptz#84] opened 2022-01-20 10:07 UTC
https://www.amazon.com/dp/B08NPGNMV8/ref=cm_sw_r_oth_api_glt_i_B76SC4A5P1B9PFY7426Q

**Comment by norihiro** [comment] 2022-02-25 14:59
I think this is a duplicate of #82.

**Comment by glikely** [comment] 2022-11-10 12:58
Duplicate of #82

**Closed by glikely** 2022-11-10 12:58 UTC
