### ISSUE TITLE
I was just getting pretty good controlling my streaming cameras with the dockable plugin...

### ISSUE THREAD

**Issue by ThomasConnolly** [glikely/obs-ptz#105] opened 2022-09-12 04:13 UTC
..then I updated OBS to version 28 & learned the great plugin is not compatible. Is there a fix in the works? I'll go back to version 27 for next Sunday's worship service, in the meantime.
Thanks.

**Comment by glikely** [comment] 2022-09-15 10:34
Duplicate of #104

**Closed by glikely** 2022-09-15 10:34 UTC
