### ISSUE TITLE
Settings is not saved after OBS exits

### ISSUE THREAD

**Issue by christianhva** [glikely/obs-ptz#70] opened 2021-11-18 07:09 UTC
OBS on Windows, version 27.1.3

**Comment by christianhva** [comment] 2021-11-18 08:05
OBS on Windows, version 27.1.3

**Comment by glikely** [comment] 2021-11-18 22:42
What settings aren't getting saved? The camera settings? The UI? Any detail you can provide would be helpful

**Comment by LighthouseMedia** [comment] 2021-11-21 18:08
Not sure if its the same issue, but it will not save preset names. I am unable to rename presents, or name presets

**Comment by glikely** [comment] 2022-01-04 12:16
I'm not able to reproduce so I'm going to close this issue. However, please reopen it if you are still having the problem and you are able to provide detailed steps to reproduce. Also please attach your obs log file as it will help in debugging.

**Closed by glikely** 2022-01-04 12:16 UTC
